#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 养老系统
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="yanglao")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void Insertjinku_Table(jinku_Table instance);
    partial void Updatejinku_Table(jinku_Table instance);
    partial void Deletejinku_Table(jinku_Table instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::养老系统.Properties.Settings.Default.yanglaoConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<zhuangtai_Table> zhuangtai_Table
		{
			get
			{
				return this.GetTable<zhuangtai_Table>();
			}
		}
		
		public System.Data.Linq.Table<jinku_Table> jinku_Table
		{
			get
			{
				return this.GetTable<jinku_Table>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.zhuangtai_Table")]
	public partial class zhuangtai_Table
	{
		
		private int _number;
		
		private string _jiashubianhao;
		
		private string _name;
		
		private string _sex;
		
		private string _phone;
		
		private string _city;
		
		private string _decs;
		
		private string _chengni;
		
		private string _qingxv;
		
		private string _Oxygen_Saturation;
		
		private string _xinlv;
		
		private string _xueya;
		
		private string _Body_Temperature;
		
		private string _xuetang;
		
		private string _Cholesterol;
		
		private string _Weight;
		
		private string _date;
		
		private string _updatezhuangtai;
		
		private string _Oid;
		
		private string _shuifei;
		
		private string _dianfei;
		
		private string _shenghuofei;
		
		private string _chongzhiliexin;
		
		private string _chongzhijine;
		
		public zhuangtai_Table()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_number", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int number
		{
			get
			{
				return this._number;
			}
			set
			{
				if ((this._number != value))
				{
					this._number = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_jiashubianhao", DbType="NVarChar(50)")]
		public string jiashubianhao
		{
			get
			{
				return this._jiashubianhao;
			}
			set
			{
				if ((this._jiashubianhao != value))
				{
					this._jiashubianhao = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(50)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this._name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sex", DbType="NChar(10)")]
		public string sex
		{
			get
			{
				return this._sex;
			}
			set
			{
				if ((this._sex != value))
				{
					this._sex = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phone", DbType="NVarChar(50)")]
		public string phone
		{
			get
			{
				return this._phone;
			}
			set
			{
				if ((this._phone != value))
				{
					this._phone = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_city", DbType="NVarChar(50)")]
		public string city
		{
			get
			{
				return this._city;
			}
			set
			{
				if ((this._city != value))
				{
					this._city = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_decs", DbType="NVarChar(50)")]
		public string decs
		{
			get
			{
				return this._decs;
			}
			set
			{
				if ((this._decs != value))
				{
					this._decs = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_chengni", DbType="NVarChar(50)")]
		public string chengni
		{
			get
			{
				return this._chengni;
			}
			set
			{
				if ((this._chengni != value))
				{
					this._chengni = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_qingxv", DbType="NVarChar(50)")]
		public string qingxv
		{
			get
			{
				return this._qingxv;
			}
			set
			{
				if ((this._qingxv != value))
				{
					this._qingxv = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Oxygen_Saturation", DbType="NVarChar(50)")]
		public string Oxygen_Saturation
		{
			get
			{
				return this._Oxygen_Saturation;
			}
			set
			{
				if ((this._Oxygen_Saturation != value))
				{
					this._Oxygen_Saturation = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_xinlv", DbType="NVarChar(50)")]
		public string xinlv
		{
			get
			{
				return this._xinlv;
			}
			set
			{
				if ((this._xinlv != value))
				{
					this._xinlv = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_xueya", DbType="NVarChar(50)")]
		public string xueya
		{
			get
			{
				return this._xueya;
			}
			set
			{
				if ((this._xueya != value))
				{
					this._xueya = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Body_Temperature", DbType="NVarChar(50)")]
		public string Body_Temperature
		{
			get
			{
				return this._Body_Temperature;
			}
			set
			{
				if ((this._Body_Temperature != value))
				{
					this._Body_Temperature = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_xuetang", DbType="NVarChar(50)")]
		public string xuetang
		{
			get
			{
				return this._xuetang;
			}
			set
			{
				if ((this._xuetang != value))
				{
					this._xuetang = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cholesterol", DbType="NVarChar(50)")]
		public string Cholesterol
		{
			get
			{
				return this._Cholesterol;
			}
			set
			{
				if ((this._Cholesterol != value))
				{
					this._Cholesterol = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Weight", DbType="NVarChar(50)")]
		public string Weight
		{
			get
			{
				return this._Weight;
			}
			set
			{
				if ((this._Weight != value))
				{
					this._Weight = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date", DbType="NVarChar(50)")]
		public string date
		{
			get
			{
				return this._date;
			}
			set
			{
				if ((this._date != value))
				{
					this._date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_updatezhuangtai", DbType="NVarChar(50)")]
		public string updatezhuangtai
		{
			get
			{
				return this._updatezhuangtai;
			}
			set
			{
				if ((this._updatezhuangtai != value))
				{
					this._updatezhuangtai = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Oid", DbType="NVarChar(50)")]
		public string Oid
		{
			get
			{
				return this._Oid;
			}
			set
			{
				if ((this._Oid != value))
				{
					this._Oid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_shuifei", DbType="NVarChar(50)")]
		public string shuifei
		{
			get
			{
				return this._shuifei;
			}
			set
			{
				if ((this._shuifei != value))
				{
					this._shuifei = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dianfei", DbType="NVarChar(50)")]
		public string dianfei
		{
			get
			{
				return this._dianfei;
			}
			set
			{
				if ((this._dianfei != value))
				{
					this._dianfei = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_shenghuofei", DbType="NVarChar(50)")]
		public string shenghuofei
		{
			get
			{
				return this._shenghuofei;
			}
			set
			{
				if ((this._shenghuofei != value))
				{
					this._shenghuofei = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_chongzhiliexin", DbType="NVarChar(50)")]
		public string chongzhiliexin
		{
			get
			{
				return this._chongzhiliexin;
			}
			set
			{
				if ((this._chongzhiliexin != value))
				{
					this._chongzhiliexin = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_chongzhijine", DbType="NVarChar(50)")]
		public string chongzhijine
		{
			get
			{
				return this._chongzhijine;
			}
			set
			{
				if ((this._chongzhijine != value))
				{
					this._chongzhijine = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.jinku_Table")]
	public partial class jinku_Table : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _number;
		
		private string _name;
		
		private string _shuifei;
		
		private string _dianfei;
		
		private string _shenghuofei;
		
		private string _jinge;
		
		private string _jiashubianhao;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnnumberChanging(int value);
    partial void OnnumberChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnshuifeiChanging(string value);
    partial void OnshuifeiChanged();
    partial void OndianfeiChanging(string value);
    partial void OndianfeiChanged();
    partial void OnshenghuofeiChanging(string value);
    partial void OnshenghuofeiChanged();
    partial void OnjingeChanging(string value);
    partial void OnjingeChanged();
    partial void OnjiashubianhaoChanging(string value);
    partial void OnjiashubianhaoChanged();
    #endregion
		
		public jinku_Table()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_number", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int number
		{
			get
			{
				return this._number;
			}
			set
			{
				if ((this._number != value))
				{
					this.OnnumberChanging(value);
					this.SendPropertyChanging();
					this._number = value;
					this.SendPropertyChanged("number");
					this.OnnumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(50)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_shuifei", DbType="NVarChar(50)")]
		public string shuifei
		{
			get
			{
				return this._shuifei;
			}
			set
			{
				if ((this._shuifei != value))
				{
					this.OnshuifeiChanging(value);
					this.SendPropertyChanging();
					this._shuifei = value;
					this.SendPropertyChanged("shuifei");
					this.OnshuifeiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dianfei", DbType="NVarChar(50)")]
		public string dianfei
		{
			get
			{
				return this._dianfei;
			}
			set
			{
				if ((this._dianfei != value))
				{
					this.OndianfeiChanging(value);
					this.SendPropertyChanging();
					this._dianfei = value;
					this.SendPropertyChanged("dianfei");
					this.OndianfeiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_shenghuofei", DbType="NVarChar(50)")]
		public string shenghuofei
		{
			get
			{
				return this._shenghuofei;
			}
			set
			{
				if ((this._shenghuofei != value))
				{
					this.OnshenghuofeiChanging(value);
					this.SendPropertyChanging();
					this._shenghuofei = value;
					this.SendPropertyChanged("shenghuofei");
					this.OnshenghuofeiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_jinge", DbType="NVarChar(50)")]
		public string jinge
		{
			get
			{
				return this._jinge;
			}
			set
			{
				if ((this._jinge != value))
				{
					this.OnjingeChanging(value);
					this.SendPropertyChanging();
					this._jinge = value;
					this.SendPropertyChanged("jinge");
					this.OnjingeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_jiashubianhao", DbType="NVarChar(50)")]
		public string jiashubianhao
		{
			get
			{
				return this._jiashubianhao;
			}
			set
			{
				if ((this._jiashubianhao != value))
				{
					this.OnjiashubianhaoChanging(value);
					this.SendPropertyChanging();
					this._jiashubianhao = value;
					this.SendPropertyChanged("jiashubianhao");
					this.OnjiashubianhaoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
